launcher_args: {experiment_name: 2022_11_01_canopus_data_ablations, 
script_name: run_scripts/train_mist.py,
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [0, 1, 2, 3],
  launch_method: local_parallel
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 6, job-name: ms-train, mem-per-cpu: 10G, time: '1-18:00:00'}
  cache-featurizers: [true]
  dataset-name: [canopus_train]

  debug: [false]
  fp-names:
  - - morgan4096
  num-workers: [12]
  persistent-workers: [false]
  seed: [1]

  gpus: [1]
  split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_100_0.csv]
  split-sizes:
  - [0.95, 0.05, 0.0]
  splitter-name: [preset]

  # Data augmentation
  augment-data: [true]
  augment-prob: [0.5]
  batch-size: [128]
  inten-prob: [0.1]
  remove-prob: [0.5]
  remove-weights: [exp]

  iterative-preds: [growing]
  iterative-loss-weight: [0.4]
  learning-rate: [0.00077]
  weight-decay: [1.0e-07]

  # Learning
  max-epochs: [600]
  min-lr: [1.0e-04]
  scheduler: [false] 
  lr-decay-time: [10000]
  lr-decay-frac: [0.95]

  # Model params
  hidden-size: [256]
  num-heads: [8]
  pairwise-featurization: [true]
  peak-attn-layers: [2]
  refine-layers: [4]
  set-pooling: [cls]
  spectra-dropout: [0.1]
  single-form-encoder: [true]
  recycle-form-encoder: [true]
  use-cls: [true]
  cls-type: [ms1]
  loss-fn: [cosine]

  # Magma args
  magma-aux-loss: [true]
  frag-fps-loss-lambda: [8]
  magma-modulo: [512]
  patience: [30]

  # Add forward specs
  add-forward-specs: [true]
  # forward-aug-folder: [data/paired_spectra/canopus_train/forward_aug_100_15000_bins_no_c_filter_75/]
  frac-orig: [0.6]

iterative_args:
  - save-dir: [split_20]
    forward-aug-folder: [data/paired_spectra/canopus_train/morgan4096_spec_preds_fold_20_0]
    split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_20_0.csv]
  - save-dir: [split_80]
    forward-aug-folder: [data/paired_spectra/canopus_train/morgan4096_spec_preds_fold_80_0]
    split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_80_0.csv]
  - save-dir: [split_60]
    forward-aug-folder: [data/paired_spectra/canopus_train/morgan4096_spec_preds_fold_60_0]
    split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_60_0.csv]
  - save-dir: [split_40]
    forward-aug-folder: [data/paired_spectra/canopus_train/morgan4096_spec_preds_fold_40_0]
    split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_40_0.csv]
