launcher_args: {experiment_name: 2022_10_27_contrastive_best_ensemble,
  script_name: run_scripts/train_contrastive.py, 
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [0, 1, 2], 
  launch_method: slurm, 
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 8, job-name: ms-train, mem-per-cpu: 12G, time: '1-18:00:00'}
  # Debug and debug overfit
  debug: [false]
  seed: [1]
  dataset-name: [csi2022]
  splitter-name: [preset]
  split-sizes:
  - [0.95, 0.05, 0]

  # Data aug
  augment-data: [true]
  augment-prob: [0.5]
  remove-prob: [0.5]
  remove-weights: [exp]
  inten-prob: [0.1]
  add-forward-specs: [true]

  # Use forward augmentations
  # forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_0/]
  frac-orig: [0.5]
  dist-name: [cosine]

  # Contrastive loss
  contrastive-loss: [nce]
  contrastive-decoy-pool: [mean]
  contrastive-latent: [h0]
  contrastive-weight: [0.6]
  contrastive-scale: [16] 
  contrastive-bias: [0.0] 
  num-decoys: [64]
  max-db-decoys: [256]
  decoy-norm-exp: [4]
  contrastive-latent-size: [null]
  negative-strategy: [hardisomer_tani_pickled]

  learning-rate: [6.0e-5]
  weight-decay: [0]
  min-lr: [5e-06] 
  scheduler: [True]
  lr-decay-time: [10000]
  lr-decay-frac: [0.801]
  patience: [10]
  max-epochs: [500]
  gpus: [1]
  batch-size: [32]
  num-workers: [8]
  persistent-workers: [false]
  cache-featurizers: [true]
  reshuffle-val: [true]

iterative_args:
  - ckpt-file: [
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_832590_dd5ac0bdbbd1cc7d1acdd795b26ba8f0/Fold_0/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_832960_a86f13fec687a0e94a8c4b58e0b3ec46/Fold_0/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_833225_577517b80b039f923660a4f980f1ce89/Fold_0/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_833487_ebeee7beaebf5449ecc8e6952a9f10b6/Fold_0/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_833729_535935379ee0aa5977eaf22c68ee984a/Fold_0/best.ckpt",
    ]
    persistent-workers: [false]
    split-file: [data/paired_spectra/csi2022/splits/csi_split_0.txt]
    forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_0/]

  - ckpt-file: [
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_833972_3dcc0a66b8db3b4214eab6265d1e5a88/Fold_1/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_834217_441b431c9952e61b297f87b0cfd7df5e/Fold_1/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_834467_fcf4c4778ae64940552d8b82eaea5328/Fold_1/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_834704_e259292abf25aeab91c9653583b45ff0/Fold_1/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_834945_a62056cca2e4769180b9221d7b285ce7/Fold_1/best.ckpt",
    ]
    persistent-workers: [false]
    split-file: [data/paired_spectra/csi2022/splits/csi_split_1.txt]
    forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_1/]

  - ckpt-file: [ 
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_835183_faf4c3fa7a6e9daaf925213608aba05a/Fold_2/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_835429_b90d05c02b8debfb32e849f4ef65822d/Fold_2/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_835664_6c48cd35957ee2610b03b6fe80bed9b2/Fold_2/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_835900_61093c7f7971b2eacffbadc9da303b6b/Fold_2/best.ckpt",
    "results/2022_10_25_mist_csi_best_ensemble/2022_10_25-1637_836130_b13883a586302d98b75b80a2b7edf344/Fold_2/best.ckpt",
    ]
    persistent-workers: [false]
    split-file: [data/paired_spectra/csi2022/splits/csi_split_2.txt]
    forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_2/]
