launcher_args: {experiment_name: 2022_10_25_mist_csi_best_ensemble,
  script_name: run_scripts/train_mist.py,
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [0],
  launch_method: slurm
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 8, job-name: ms-train, mem-per-cpu: 8G, time: '1-18:00:00'}

  cache-featurizers: [true]
  dataset-name: [csi2022]

  # Debug
  debug: [false]
  fp-names:
  - - csi
  num-workers: [8]
  persistent-workers: [false]
  seed: [1,2,3, 4,5]
  loss-fn: [cosine]

  gpus: [1]
  split-file: [data/paired_spectra/csi2022/splits/csi_split_0.txt]
  split-sizes:
  - [0.95, 0.05, 0.0]
  splitter-name: [preset]

  # Data augmentation
  augment-data: [true]
  augment-prob: [0.5]
  batch-size: [128]
  inten-prob: [0.1]
  remove-prob: [0.5]
  remove-weights: [exp]

  # No iterative preds for debug
  iterative-preds: [growing]
  iterative-loss-weight: [0.6]
  learning-rate: [0.00026]
  lr-decay-frac: [0.97]
  weight-decay: [1.0e-07]

  # Learning
  max-epochs: [600]
  min-lr: [5e-06] 
  scheduler: [true] 
  lr-decay-time: [10000]

  # Model params
  hidden-size: [256]
  num-heads: [8]
  pairwise-featurization: [true]
  peak-attn-layers: [3]
  refine-layers: [5]
  set-pooling: [cls]
  spectra-dropout: [0.1]
  single-form-encoder: [true]
  use-cls: [true]
  cls-type: [ms1]

  # Magma args
  magma-aux-loss: [true]
  frag-fps-loss-lambda: [2]
  magma-modulo: [512]
  patience: [50]

  # adding forward specs
  add-forward-specs: [true]
  forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_0/]
  frac-orig: [0.5]
  reshuffle-val: [true]
  recycle-form-encoder: [true]

iterative_args:
  - split-file: [data/paired_spectra/csi2022/splits/csi_split_0.txt]
    forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_0/]

  - split-file: [data/paired_spectra/csi2022/splits/csi_split_1.txt]
    forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_1/]

  - split-file: [data/paired_spectra/csi2022/splits/csi_split_2.txt]
    forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_2/]
