launcher_args: {experiment_name: 2022_10_25_mist_hyperopt_contrastive, 
  script_name: run_scripts/hyperopt_contrastive.py, 
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [1,2,3], 
  launch_method: local, 
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 8, job-name: ms-train, mem-per-cpu: 12G,
    time: '1-18:00:00'}

  debug: [false]
  seed: [1]
  dataset-name: [csi2022]
  splitter-name: [preset]
  split-file: [data/paired_spectra/csi2022/splits/csi_split_0.txt]
  split-sizes:
  - [0.95, 0.05, 0.0]

  # Data aug
  augment-data: [true]
  augment-prob: [0.5]
  remove-prob: [0.5]
  remove-weights: [exp]
  inten-prob: [0.1]
  add-forward-specs: [true]

  # Use forward augmentations
  forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_0/]
  frac-orig: [0.1]
  dist-name: [cosine]

  # Contrastive loss
  contrastive-loss: [nce]
  contrastive-decoy-pool: [mean]
  contrastive-latent: [h0]
  contrastive-weight: [0.6]
  contrastive-scale: [10] 
  contrastive-bias: [0.1] 
  num-decoys: [64]
  max-db-decoys: [256]
  decoy-norm-exp: [4]
  contrastive-latent-size: [null]
  negative-strategy: [hardisomer_tani_pickled]


  learning-rate: [0.0007]
  weight-decay: [1.0e-07]
  min-lr: [5e-06] 
  scheduler: [true]
  lr-decay-time: [10000] 
  patience: [10]
  max-epochs: [200]
  gpus: [1]
  batch-size: [32]
  num-workers: [12]
  persistent-workers: [false]
  cache-featurizers: [true]

iterative_args:
  - ckpt-file: ['results/2022_10_25_mist_best_params/2022_10_25-0848_266173_3afb73eaf30275894a8c7d2b6fb93a8c/Fold_0/best.ckpt']
    persistent-workers: [false]

    # Hyperopt args
    cpus-per-trial: [12]
    gpus-per-trial: [1]
    num-h-samples: [100]
    grace-period: [900]
    max-concurrent: [10]
    tune-save: [true]
