launcher_args: {experiment_name: model_train_demos, 
  script_name: run_scripts/train_ffn_binned.py,
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [1,2,3],
  launch_method: local
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 6, job-name: ms-train, mem-per-cpu: 10G, time: '1-18:00:00'}

  cache-featurizers: [true]
  dataset-name: [canopus_train_public]

  # Debug
  debug: [false]
  fp-names:
  - - morgan4096
  num-workers: [12]
  persistent-workers: [false]
  seed: [1]

  gpus: [0]
  split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_100_0.csv]
  #split-sizes:
  #- [0.95, 0.05, 0.0]
  splitter-name: [preset]

  # Data augmentation
  augment-data: [false]
  augment-prob: [0.5]
  batch-size: [128]
  inten-prob: [0.1]
  remove-prob: [0.5]
  remove-weights: [exp]

  iterative-loss-weight: [0.5]
  iterative-preds: [none]
  learning-rate: [0.00087]
  weight-decay: [1.0e-07]

  # Learning
  max-epochs: [600]
  min-lr: [5e-06] 
  scheduler: [false] 
  lr-decay-time: [50]
  min-lr: [1.0e-05]
  lr-decay-time: [10000]

  # Model params
  hidden-size: [512]
  num-spec-layers: [2]
  num-bins: [11000]
  spectra-dropout: [0.3]
  patience: [60]
  loss-fn: [cosine] 
  
  add-forward-specs: [false]

  # No adding forward specs
  #forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_0/]
  #frac-orig: [0.5]

iterative_args:
  - save-dir: [ffn_fp_model]
    split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_100_0.csv]
