launcher_args: {experiment_name: 2023_04_30_canopus_train_hyperopt_xformer,
  script_name: run_scripts/hyperopt_xformer.py,
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [0,1,2], 
  launch_method: local
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 6, job-name: ms-train, mem-per-cpu: 10G,
    time: '1-18:00:00'}

  cache-featurizers: [true]
  dataset-name: [canopus_train]

  # Debug
  debug: [false]
  fp-names:
  - - morgan4096
  num-workers: [0]
  persistent-workers: [false]
  seed: [1]

  gpus: [1]
  split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_100_0.csv]
  split-sizes:
  - [0.95, 0.05, 0.0]
  splitter-name: [preset]

  # Data augmentation
  augment-data: [false]
  augment-prob: [0.5]
  batch-size: [32]
  inten-prob: [0.1]
  remove-prob: [0.5]
  remove-weights: [exp]

  # No iterative preds
  iterative-preds: [none]
  learning-rate: [0.0007]
  weight-decay: [1.0e-07]

  # Learning
  max-epochs: [600]
  min-lr: [5e-06] 
  scheduler: [true] 
  lr-decay-time: [10000] 

  # Model params
  hidden-size: [256]
  num-spec-layers: [3]
  spectra-dropout: [0.1]
  patience: [60] 

iterative_args:
  - iterative-preds: [none]
    iterative-loss-weight: [0.5] 
    loss-fn: [cosine]

    # Model params
    hidden-size: [256]
    num-spec-layers: [3]
    spectra-dropout: [0.1]

    # LR
    learning-rate: [7.0e-4]
    lr-decay-frac: [0.95] 

    # High batch cosine
    batch-size: [64] 

    # No adding ofrward specs
    add-forward-specs: [false]
    forward-aug-folder: [data/paired_spectra/csi2022/csi_spec_preds_fold_0/]
    frac-orig: [0.5]

    # Hyperopt args
    cpus-per-trial: [8]
    gpus-per-trial: [0.5]
    num-h-samples: [100] 
    grace-period: [900]
    max-concurrent: [10]